### ISSUE TITLE
Bug with celdaTsne following DecontX

### ISSUE THREAD

**Issue by cmerenstein** [campbio/celda#106]
When running celdaTsne using counts from the decontX function, I get the following error:

```
 *** caught segfault ***
address 0x8, cause 'memory not mapped'

Traceback:
 1: Rtsne_cpp(X, dims, perplexity, theta, verbose, max_iter, is_distance,     Y_init, init, stop_lying_iter, mom_switch_iter, momentum,     final_momentum, eta, exaggeration_factor)                      
 2: Rtsne.default(norm, pca = do.pca, max_iter = max.iter, perplexity = perplexity,     check_duplicates = FALSE, is_distance = FALSE, initial_dims = initial.dims)                                        
 3: Rtsne::Rtsne(norm, pca = do.pca, max_iter = max.iter, perplexity = perplexity,     check_duplicates = FALSE, is_distance = FALSE, initial_dims = initial.dims)                                         
 4: calculateTsne(norm, do.pca = FALSE, perplexity = perplexity,     max.iter = max.iter, seed = seed)                                                                                                     
 5: celdaTsne(counts = new.counts$res.list$est.nativeCounts, celda.mod = celda.20.decontx)
 6: celdaTsne(counts = new.counts$res.list$est.nativeCounts, celda.mod = celda.20.decontx)
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault
```
The following code reproduces this error (I can email the .rds files):

```library(celda)

## original count matrix, filtered to >2 counts in >2 cells
cts = readRDS("filtered_counts.rds")

## celda_CG model K = 20 L = 75
celda.mod = readRDS("celda.20.rds")

## object returned by DecontX
new.counts = readRDS("new.counts.rds")

## just the count matrix from the DecontX object
new.cts = new.counts$res.list$est.nativeCounts

## celda_CG re-run with the count matrix from new.counts
decontx.mod = readRDS("celda.20.decontx.rds")

celdaTsne(counts = new.cts, celda.mod = decontx.mod)
```
I tried setting the storage mode of new.cts to be integer, but this still gave me the same error.

**Comment by zhewa** [comment]
Hi @cmerenstein 
I ran your code using the latest build of celda (master branch) and did not see the `Segmentation fault` error. However, I do see another error saying `Error in na.fail.default(X) : missing values in object` when running `celdaTsne` using `new.cts`. This is because there are columns that are all 0s in `new.cts` after rounding. `celdaTsne` automatically rounds the input count matrix to integers and then do normalization. `NA` are introduced when a column of 0s is divided by 0. The fix is to first round `new.cts` and then run `celda_CG` on that and then celdaTsne should work fine. We will add a check in `fastNormProp` to make sure it does not divide by 0.
https://github.com/campbio/celda/blob/7e9500bf6c8fa9ddb94a6db88deeb149c949fb91/src/matrixNorm.cpp#L20
Here `cs[i] + alpha_tot` could be 0.

**Comment by zhewa** [comment]
#109

**Comment by cmerenstein** [comment]
Hey @zhewa ,

Now when I run `celdaTsne`, with or without having run DecontX before, I get the following error:
```
Error in (function (classes, fdef, mtable)  :                                  
unable to find an inherited method for function 'celdaTsne' for signature '"missing"'
```

I re-built celda from the master branch (changing only the DESCRIPTION to be R >= 3.5 instead of 3.6), but this error still comes up. I get this error on scripts that have worked in the past, so I don't think it has to do with how I'm running `celdaTsne`

**Comment by zhewa** [comment]
Hi @cmerenstein 

Sorry for the confusion. On April 10, we pushed a major update to celda master branch which reformatted almost all of the variable/function names. This means the names for all the slots in the `celda_model` and `celda_list` objects have been changed. These objects generated from previous celda versions will not be compatible with latest celda from now on.

Can you try install from 20190409_master branch and redo the analysis?
```
library(devtools)
install_github("campbio/celda@20190409_master")
```

Thank you,
Zhe

**Comment by cmerenstein** [comment]
Zhe,

Thanks for the help. When I redo the analysis it works, as long as I remove any columns that have a sum of 0 counts.
