### ISSUE TITLE
potential improvement on celdaTsne

### ISSUE THREAD

**Issue by Irisapo** [campbio/celda#113]
Hey, would it be good to make celdaTsne take objects generated from simulateCells? 
I find sometimes I just want to test a simulated dataset, and want to see a tsne plot, but I cannot feed the object directly to celdaTsne. I had to run Celda on the simulated data to get a new celda object then throw it into the function to make a tsne plot, which is not necessary sometimes.

**Comment by zhewa** [comment]
Hi @Irisapo 

I think if you want to get the tSNE of any count matrix you might want to just run `Rtsne`? Of course you might want to normalize the data before doing that. I don't know if there is anything else we could add on top of `Rtsne` except normalization for doing this type of job.

Zhe
