### ISSUE TITLE
Error in differentialExpression

### ISSUE THREAD

**Issue by cmerenstein** [campbio/celda#127]
When trying to run the differentialExpression command in celda I get the following error:
```
Error in assayNames(x) : could not find function "assayNames"
```

The following code is enough to generate the error (I will send you files separately):
```
library(celda)

## counts matrix
cts = readRDS("filtered_counts.rds")

## celda object
celda.20 = readRDS("celda.20.rds")

differentialExpression(counts = cts, celda.mod = celda.20, c1 = 3 )

```

I'm using campbio/celda@20190409_master as my version of celda.

**Comment by zhewa** [comment]
Hi @cmerenstein 

Can you run `library(SummarizedExperiment)` before you run `differentialExpression()`. I think this error is somewhere within `MAST`'s package dependency.

**Comment by cmerenstein** [comment]
That fixed it. Thank you!
