### ISSUE TITLE
seed setting for simulation functions 

### ISSUE THREAD

**Issue by Irisapo** [campbio/celda#133]
Hey I just realized (thanks to bioconductor latest report) that all the seed arguments fed to the simulation functions have been removed, including decontX. 
I am wondering why seed argument was removed from all functions, while seed is to promise consistency and reproductivity.

**Comment by zhewa** [comment]
Hi @Irisapo

The use of `set.seed()` is not allowed for Bioconductor packages. We have removed them for now for getting our package in the Bioconductor repository.

**Comment by Irisapo** [comment]
ok, got it. thanks for the explanation!
