### ISSUE TITLE
Celda does not throw error or stop when supposed to do 

### ISSUE THREAD

**Issue by Irisapo** [campbio/celda#152]
Celda does not throw error when counts matrix has any row(s)/column(s) has all 0 count cross the whole dataset.   

I think all functions that wrapped upon celda_C, celda_G, celda_CG have this issue, although I only have tested celda_C, celda_G, celda_CG and recursiceSplitModule. 

One example code here: 
```
sim = simulateCells( model = "celda_CG" ) 
sim$counts[ 10, ] = 0 
sum( rowSums( sim$counts) == 0 )   # showing one row has all 0 count cross the whole dataset 

celda_CG( sim$counts, K = 5, L = 6)  #however it didn't stop the process or throw an error while it's supposed to be
```

**Comment by zhewa** [comment]
#153
