### ISSUE TITLE
Alternate headings for plotDimReduceFeature?

### ISSUE THREAD

**Issue by cmerenstein** [campbio/celda#156]
In plotDimReduceFeature, the headings for each of the little plots matches the names of the features that you give it. A lot of times this is the ensembl gene ID, which isn't all that useful to look at.

Is it possible to also give the function a list of headings that correspond to the features? It would be nice to be able to easily make the plots with the gene symbol as the headings rather then the ensembl id.

**Comment by zhewa** [comment]
#182
