### ISSUE TITLE
Make use of SingleCellExperiment for data input and output

### ISSUE THREAD

**Issue by zhewa** [campbio/celda#181]
Right now `celda` uses the `celda_CG` (or `celda_C`/`celda_G`) `S4` objects for storing the celda model results including `sampleLabel`, `params`, `names`, `completeLogLik`, `finalLogLik`, and cell and gene cluster assignments. **This object does not store the count matrix that was used to generate these results**.

`SingleCellExperiment` is a powerful `S4` object container developed by Bioconductor team specific for scRNA-seq data. It is well maintained. **It has a `metadata` slot for storing named list**. Using `SingleCellExperiment` object as the standard container in `celda` and use it for the inputs and outputs of certain `celda` functions should prove beneficial in the long term in terms of package maintenance, development, interoperability and accessibility. 

A few thoughts on how to implement this in a function (for example when running `celda_CG` or `celdaGridSearch`):
1. Use `SingleCellExperiment` as the basic input object instead of a `matrix` object of count matrix.
2. Put `celdaList` object (in `list` format) into the `metadata` slot of `SingleCellExperiment`. The use of a `celdaList` object instead of `celda_CG`/`celda_C`/`celda_G` objects is probably safer because user might use the `celdaGridSearch` function. This step will require a lot of reformatting to keep things clean and simple (convert the `S4` objects to `list`). A well-thought-out list structure that encompasses slots for all possible cases or results is needed.
3. Propagate any results generated by `celda` functions to the `metadata` slot of the `SingleCellExperiment` object using the list structure mentioned in 2.
4. Return the `SingleCellExperiment`. 

This way the count matrix, annotations, and `celda` results are all included in one object. And we don't need to worry about the `countChecksum`. And we can easily pull out gene annotations and use gene symbols for plotting.

**Comment by ncasiraghi** [comment]
Hi zhewa, I am trying to use the decontX function, can I use SingleCellExperiment data as input?
I installed celda 1.5.5 from github.
thanks

**Comment by zhewa** [comment]
Hi Nocola,


Yes. You can use SingleCellExperiment data as input. You can check the details about decontX function by typing ?decontX in R.


Zhe




------------------&nbsp;Original&nbsp;------------------

**Comment by joshua-d-campbell** [comment]
Also take a look at our new vignette on Bioconductor:

https://www.bioconductor.org/packages/release/bioc/vignettes/celda/inst/doc/decontX.pdf

You may need to re-install the latest version of celda if you previously installed it more than a month ago.
