### ISSUE TITLE
Tutorial (vignette) for analysis of a real dataset using celda

### ISSUE THREAD

**Issue by zhewa** [campbio/celda#189]
Right now the vignette in `celda` only has example for simulated data. For first-time users this is not enough when they are trying to analyze real data. For example data filtering is not included in the current vignette. A vignette showing how to run `celda` on real data should be provided. Maybe subset genes and a few cells from each cell type in PBMC 3K data and use it as example data.

**Comment by bjstewart1** [comment]
Agree - the bottleneck with this tool is speed on most datasets, and the data needs to be subset either on genes or cells in order to run. 
Would be useful if the authors could put out some opinions on best practice.

**Comment by joshua-d-campbell** [comment]
Thanks for the suggestions. We have added a tutorials for celda and decontX on our new website:

http://celda.camplab.net/

Specifically, analysis of the PBMC 3K dataset can be found here:

http://celda.camplab.net/v1.9.2/articles/articles/celda_pbmc3k.html
