### ISSUE TITLE
Details on how DecontX works

### ISSUE THREAD

**Issue by seanken** [campbio/celda#196]
Hope all is well! Can't find anywhere details on how DecontX works under the hood (the underlying mathematical model/algorithm). Is there such a document online, or could someone explain it (would be useful to many here, I am sure). Might be I am just missing it (if so, sorry for the question!)? If so would be great to add a pointer to the description on the ReadMe page. Just would like to know what I am doing to my data/ might be useful for debugging some issues we've had. Thanks!

**Comment by joshua-d-campbell** [comment]
Hi Sean,
I apologize for the lack of public details. We are very close to getting the full algorithm up on bioRxiv. I will actually be presenting this at the Broad tomorrow during the HTAN face-to-face meeting. Happy to give you more details then. Either way, if you are running into errors or strange behaviors, we would definitely like to know about them.

**Comment by seanken** [comment]
Thanks for the quick reply! That would be great--though not sure what you mean by HTAN? 

On our end, we are trying to use the tool to help understand ambient RNA in different single cell technologies (10X, Drop-seq, etc) for a single cell comparison we recently submitted. Seems like it might be working well for some datasets, but for others it will often flag an entire cell type as being extremely high in contamination. I suppose it is possible something biological is happening there (some cell types having more contamination due to cell quality, some biological reason, etc, though don't think there is any obvious quality metric/biology to explain this), but seems a bit suspicious to us. Could be I am doing something wrong with the program, or it could be issues with the clustering (Maybe we need to merge cell types that are too similar, or further subcluster?). Was just hoping for anything that might point us in the right direction.

**Comment by joshua-d-campbell** [comment]
The model is now up on bioRxiv:

https://www.biorxiv.org/content/10.1101/704015v1

**Comment by seanken** [comment]
Hey,

Thanks! Excited to read it!

Best wishes,

Sean
