### ISSUE TITLE
Sparse matrix

### ISSUE THREAD

**Issue by ltosti** [campbio/celda#199]
Hi there,

Does DecontX take sparse matrix as input?

Thank you!

**Comment by zhewa** [comment]
Hi @ltosti,

Right now DecontX only takes `matrix` object as input. However, you can read in sparse matrix in R using the `readMM` function in `Matrix` package and then convert it to a `matrix` object using `as.matrix` function.

**Comment by Irisapo** [comment]
Hey @ltosti

Sparse matrix cannot be taken by DecontX yet, but it will definitely be in the near future. 
For now please do as @zhewa suggested.
