### ISSUE TITLE
TENxPBMCData

### ISSUE THREAD

**Issue by definitelysean** [campbio/celda#203]
In lieu of the pre-processed, manually curated datasets we've been using for vignetttes / tutorials, directly load the dataset from the T[ENxPBMCData package](https://bioconductor.org/packages/release/data/experiment/html/TENxPBMCData.html)

One up-front test we can do would be to pull the data in from this package, do our usual filtering per @ykoga07 's criteria, and then use `all.equal()` or the like to ensure that the vignettes / example figures should come out exactly the same in the end.

**Comment by joshua-d-campbell** [comment]
This has been done for DecontX. However it would take to long for Celda currently.
