### ISSUE TITLE
semiPheatmap

### ISSUE THREAD

**Issue by ykoga07** [campbio/celda#206]
The documentation for semiPheatmap is available upon installation, but the function is not.

Code:
semiPheatmap()
Error in semiPheatmap() : could not find function "semiPheatmap"

?semiPheatmap
semiPheatmap               package:celda               R Documentation

A function to draw clustered heatmaps.

**Comment by zhewa** [comment]
Hi @ykoga07 
If you really want to use the function `semiPheatmap` you can do `celda::semiPheatmap()`. The thing is this function do not have executable examples so I did not make it an exported function. Maybe @Irisapo should look into this. I think she added this function in the first place. Making the documentation of this function unavailable to the user seems like an inadequate fix so I'm leaving it as is.

**Comment by ykoga07** [comment]
Thanks @zhewa for the response.

It actually doesn't seem like the semiPheatmap function is accessible with that command:

celda::semiPheatmap(mat = pbmc)
Error: 'semiPheatmap' is not an exported object from 'namespace:celda'

**Comment by zhewa** [comment]
Sorry @ykoga07  I meant `celda:::semiPheatmap()`

**Comment by Irisapo** [comment]
Hey @ykoga07 , 
I will try to work on it to make it an exported function along with documentation.
You have to use it the way @zhewa stated before that happens...

**Comment by Irisapo** [comment]
Hey @ykoga07  
Actually there is an exported function plotHeatmap from Celda to do the semi-heatmap, which takes a count matrix, [row label and/or column label]. Give it a try and let me know whether this is what you wanted

**Comment by Irisapo** [comment]
@zhewa  I saw the documentation as well and it seems to have documented the wrong function. 
You might want to change the Documentation of the "semiHeatmap" part and make it compatible with the "plotHeatmap" function.
