### ISSUE TITLE
reorder functions should be public

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/celda#209]
Functions like ".reorderCeldaCG" should be exported so that they can be called after applying recursivesplit functions with reorder=FALSE

**Comment by zhewa** [comment]
The exported function `reorderCelda` has been added (#327) to automatically reorder the cell cluster and/or feature module labels. `recodeClusterZ` and `recodeClusterY` can be used to manually set the cell cluster and feature module labels.
