### ISSUE TITLE
DecontX adding counts?

### ISSUE THREAD

**Issue by juliaszusz** [campbio/celda#254]
Hi, I have been testing out using DecontX for ambient RNA correction. I wanted to see what genes and counts were being removed from the data, so I subtracted the corrected count matrix from the original count matrix and expected that there should only be positive values from this (more counts in the original matrix than the corrected matrix). I found that for many genes there were higher counts post-analysis than there were in the original matrix, which would indicate to me that counts were being added. For around 9,000 of my 20,000 detected genes the overall change is negative (more counts in the corrected matrix). Could you comment on/explain this at all? Thanks!

**Comment by joshua-d-campbell** [comment]
Hi @juliaszusz. Thanks for trying it out. Yes, the decontaminated counts should be less than or equal to the original counts. See below for an example using PBMC data. Can you describe the matrix that you used as input into DecontX and what type of data it is (e.g. 10X)? We recently pushed a major update to increase the speed and operate from a SingleCellExperiment object. Can you make sure you are using the most recent version? 

```
> library(TENxPBMCData)
> library(celda)
> pbmc = TENxPBMCData("pbmc3k")
> pbmc = decontX(pbmc)
--------------------------------------------------
Starting DecontX
--------------------------------------------------
Tue Jan 28 17:16:38 2020 .. Analyzing all cells
Tue Jan 28 17:16:39 2020 .... Converting to sparse matrix
Tue Jan 28 17:16:52 2020 .... Estimating cell types with Celda
Tue Jan 28 17:16:56 2020 ...... Collapsing features into 50 modules
Tue Jan 28 17:19:17 2020 ...... Reducing dimensionality with UMAP
Tue Jan 28 17:19:24 2020 ...... Determining cell clusters with DBSCAN (Eps=1)
Tue Jan 28 17:19:24 2020 .... Estimating contamination
Tue Jan 28 17:19:25 2020 ...... Completed iteration: 10 | converge: 0.02519
Tue Jan 28 17:19:26 2020 ...... Completed iteration: 20 | converge: 0.01038
Tue Jan 28 17:19:27 2020 ...... Completed iteration: 30 | converge: 0.00596
Tue Jan 28 17:19:28 2020 ...... Completed iteration: 40 | converge: 0.003929
Tue Jan 28 17:19:29 2020 ...... Completed iteration: 50 | converge: 0.002822
Tue Jan 28 17:19:30 2020 ...... Completed iteration: 60 | converge: 0.002135
Tue Jan 28 17:19:31 2020 ...... Completed iteration: 70 | converge: 0.001734
Tue Jan 28 17:19:32 2020 ...... Completed iteration: 80 | converge: 0.001681
Tue Jan 28 17:19:33 2020 ...... Completed iteration: 90 | converge: 0.001665
Tue Jan 28 17:19:35 2020 ...... Completed iteration: 100 | converge: 0.001277
Tue Jan 28 17:19:36 2020 ...... Completed iteration: 110 | converge: 0.001035
Tue Jan 28 17:19:36 2020 ...... Completed iteration: 114 | converge: 0.0009883
--------------------------------------------------
Completed DecontX. Total time: 3.145589 mins
--------------------------------------------------
> sum(counts(pbmc) < decontXcounts(pbmc))
[1] 0
```
