### ISSUE TITLE
dependency on BiocNeighbors?

### ISSUE THREAD

**Issue by Irisapo** [campbio/celda#261]
Does anyone know where we need to depend on BiocNeighbors package?
The problem happens in travis build, saying 
`installation of package ‘BiocNeighbors’ had non-zero exit status`
Even though I was able to (re)build and install celda on my local. 

I cannot find BiocNeighbors in our NAMESPACE either. Is this something to do with travis setup?

**Comment by Irisapo** [comment]
@zhewa

**Comment by joshua-d-campbell** [comment]
This was an error in their package which can be circumvented by installing from github in the travis build
