### ISSUE TITLE
Should there be seed setting for recursiveSplitModule / recursiveSplitCell ??

### ISSUE THREAD

**Issue by Irisapo** [campbio/celda#263]
Even though what is actually stochastic that needs seed setting is the celda_CG/celda_G/celda_C functions that were wrapped into recursiveSplitModule / recursiveSplitCell. Should we still set seed to them so that the results are more reproducible?

**Comment by Irisapo** [comment]
This concern from me is that I don't know how set.seed() outside of the recursiveSplitModule / recursiveSplitCell affects the with_seed() function used inside of celda_CG/celda_G/celda_C

**Comment by zhewa** [comment]
`seed` arguments added to `recursiveSplitModule` and `recursiveSplitCell`
