### ISSUE TITLE
Cannot run decontX on SCE dataset.

### ISSUE THREAD

**Issue by piyushjo15** [campbio/celda#268]
Hi. i am trying to test DecontX for my dataset. Unfortunately, I am not able to run it. First there is no vignette showing how to run on any real data from 10x, plus this information is also missing from the MS. 

Second, i tried following the TENxPBMC dataset example in one of the issue post, but I get the following error. 
```
--------------------------------------------------
Start DecontX. Decontamination
--------------------------------------------------
Error in round(counts) : non-numeric argument to mathematical function
```
The I tried running it by extracting the sparse matrix from SCE dataset and got the below error.
```
--------------------------------------------------
Start DecontX. Decontamination
--------------------------------------------------
Error in storage.mode(counts) <- "integer" : 
  no method for coercing this S4 class to a vector
```
What I am doing wrong? Help !
Piyush

**Comment by piyushjo15** [comment]
Ok. So when I installed using the "BiocManager" way it didn't work.
But when I installed using the github way, it runs.

**Comment by zhewa** [comment]
Hi @piyushjo15 

We recommend using the stable release of [celda package](http://bioconductor.org/packages/release/bioc/html/celda.html) from Bioconductor and follow the vignette available there. The most recent master branch release on github is still under development. If you really want to test it out you can check out this [vignette](https://github.com/campbio/celda/blob/28006cbdff79e43946df3ea8508f4f79b4ff98c5/vignettes/decontX.Rmd). As you mentioned ignore the installation from Bioconductor and install directly from github.

**Comment by Cumol** [comment]
decontX seems to expect a matrix for the `counts` argument it does not however work with `sparseMatrix` from the `Matrix` package

**Comment by joshua-d-campbell** [comment]
Hi @Cumol 
If you try installing the new version of celda from Github using the following command:

```
library(devtools)
install_github("campbio/celda")
```

It will be able to work with a sparse matrix. This version will be pushed out to Bioconductor later this month.
