### ISSUE TITLE
DecontX before or after integrating datasets?

### ISSUE THREAD

**Issue by Cumol** [campbio/celda#273]
I am using Harmony to integrate multiple datasets and wondering when the best time to use Decontx is.

Should I run Decontx on the raw counts of each individual dataset before I combine and integrate them with Harmony? Should I use it on the combined dataset before the integration? Or maybe on the integrated values?

I also saw that it is possible to give DecontX cell labels (clusters) to run it with. Does that make sense when using dataset integration? I could imagine running integration and clustering first (without decontx) and then run decontx with the assigned clusters. It might however be problematic if some cells were assigned a wrong cluster before decontx...

Any opinions on this matter?

**Comment by joshua-d-campbell** [comment]
Hi @Cumol,
Great question. Contamination generally occurs within cells that were dissociated/processed together and run within the same assay (i.e. within a 10X channel). We therefore recommend to run DecontX on each sample/channel within each dataset separately and then combine the decontaminated counts for downstream analysis.

If counts of cells from different assays have already been combined in your SCE object, you can use the 'batch' parameter to tell decontX to estimate contamination those groups of cells separately.

We have recently released a faster version with improved plotting functions and vignettes. I would recommend to install directly from GitHub if you have not done so already for now (until the newest Bioconductor release). Here is the command to install from GitHub that will also build the new vignette (may take ~5 min to run):

```
library(devtools)
install_github("campbio/celda", build_vignettes = TRUE)
```

The new vignette can be accessed:

```
library(celda)
vignette("decontX")
```

**Comment by Cumol** [comment]
Thank you for your response. I will give it a try!

**Comment by Cumol** [comment]
I am getting the following error when installing:

```
E> clang++ -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/Rcpp/include" -I"/Library/Frameworks/R.framework/Versions/3.6/Resources/library/RcppEigen/include" -I/usr/local/opt/gettext/include -I/usr/local/opt/llvm/include -I/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include -fopenmp  -fPIC  -Wall -g -O2  -c DecontX.cpp -o DecontX.o
E> clang: error: unsupported option '-fopenmp'
```

Now I remember that I got the error before when I tried to install celda from github. The installation from bioconductor worked. 

This ended up solving the issue: https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

And now there was an issue creating the vignettes: 

```
 --- re-building ‘decontX.Rmd’ using rmarkdown
   Warning in engine$weave(file, quiet = quiet, encoding = enc) :
     Pandoc (>= 1.12.3) and/or pandoc-citeproc not available. Falling back to R Markdown v1.
   Quitting from lines 52-56 (decontX.Rmd) 
   Error: processing vignette 'decontX.Rmd' failed with diagnostics:
   there is no package called 'TENxPBMCData'
   --- failed re-building ‘decontX.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘decontX.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error: Failed to install 'celda' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> Quitting from lines 52-56 (decontX.Rmd) 
E> Error: processing vignette 'decontX.Rmd' failed with diagnostics:
E> there is no package called 'TENxPBMCData'
E> --- failed re-building ‘decontX.Rmd’
E> 
E> SUMMARY: processing the following file failed:
E>   ‘decontX.Rmd’
E> 
E> Error: Vignette re-building failed.
E> Execution halted
In addition: There were 15 warnings (use warnings() to see them)
```
fixed by installing the missing package:

`BiocManager::install("TENxPBMCData")`

**Comment by joshua-d-campbell** [comment]
Thank you for the feedback! We have added the install command to the vignette (if the package is not already available) and linked to the Rcpp fix in the README. Hopefully that will help streamline the process for future users.

**Comment by Cumol** [comment]
I assume that DecontX is supposed to be used on the raw count matrix before any kind of filtering etc. am I right in this assumption?

If I understood correctly, it also relies on some form of dimension reduction to find out which cell populations could be the "contaminators" or a given cell. That means that the raw count matrix should already be enough to separate the cells into cell populations that are then used for the correction.

This is sadly not always the case. In my datasets there are some examples when a UMAP/tSNE/PCA of the raw count matrix does not result in something meaningful. Only after normalization, and variable gene detection I get cell populations that are useful. 

My question is. How do I deal with such data?

One though was to do the full integration and clustering pipeline and then use the discovered clusters as input into DecontX to "clean up" the counts for each cell for a possible cleaner second run of the pipeline.

Does that make sense?

**Comment by joshua-d-campbell** [comment]
Yes, DecontX is supposed to operate on the raw (i.e. unnormalized) counts matrix. If no cluster labels are supplied via the `z` argument, then DecontX will normalize the data use the `logNormCounts` function from scater, generate a UMAP using the `runUMAP` function from scater (uses PCA to first reduce the dimensionality of the data), and cluster the cells using `dbscan`. DecontX will then go back to the raw counts to estimate contamination with these cluster labels. 

Therefore, you do not need to normalize the data yourself. If the clusters that DecontX generates do not capture the major cell types present in your dataset, you can run through your preferred clustering approach and then run DecontX with setting the `z` parameter to your cluster labels. We recommend that the cluster labels reflect broad cell types (usually represented by different major groups on the UMAP) rather than clusters within different cell types. For example, you may want to keep all T-cells in the same cluster rather than having separate clusters for subsets of T-cells.
