### ISSUE TITLE
NAs produced by integer overflow

### ISSUE THREAD

**Issue by ncasiraghi** [campbio/celda#287]
Hi, I tried to use the function decontX passing as input a SingleCellExperiment object.
I got the following error:
```R
--------------------------------------------------
Starting DecontX
--------------------------------------------------
Thu May 14 09:22:00 2020 .. Analyzing all cells
Thu May 14 09:22:00 2020 .... Converting to sparse matrix
Error: subscript contains NAs
In addition: Warning messages:
1: In (ans - 1L) * dim[, along] : NAs produced by integer overflow
2: In (ans - 1L) * dim[, along] + aind[, along] :
  NAs produced by integer overflow
```  

thanks a lot for any help

**Comment by zhewa** [comment]
Hi Nicola,


Can you send me the commands and ideally the SCE object you used to run decontX? Without the exact SCE object to reproduce this error, I might not be able to help you more.


Zhe




------------------&nbsp;Original&nbsp;------------------

**Comment by ncasiraghi** [comment]
thanks for the fast reply.

Not sure if I can share the SCE (let me check this please). 
Meanwhile these are commands that I used:
```R
# create SCE object
sce <- read10xCounts(samples = cellranger_h5.file, type = 'HDF5',col.names = T)
# run decontX
dec <- decontX(x = sce)
```

**Comment by zhewa** [comment]
Hi Nocola,


I am not able to reproduce the error you reported using the example data from&nbsp;read10xCounts documentation. My guess is the dataset you are trying to process is quite large and it failed to be loaded to memory during the conversion to dgCMatrix step. Maybe you can try restart your Rstudio and free up some memory before you run decontX?


Can you try this after you run read10xCounts:


assay(sce) <- methods::as(assay(sce), "dgCMatrix")


If this works maybe you can successfully run decontX next.


Best,
Zhe


------------------&nbsp;Original&nbsp;------------------
