### ISSUE TITLE
Error in if (min(x) == 0) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by peerkarmaus** [campbio/celda#295]
Hi celda team, 
Thank you for providing such a great library. I am using the decontX function to decontaminate scRNA-Seq from whole tissues. 

I use the following code (I have attached the mat in this [mat.RData](https://nih.box.com/shared/static/1m37f57jo5ac9lcil2snvp4cy4vqzqch.rdata) file):
`counts_decont <- decontX(counts = mat, z = NULL, maxIter = 100) `

This is the output I get:

--------------------------------------------------
Start DecontX. Decontamination
--------------------------------------------------
Error in if (min(x) == 0) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In log(t(eta)[globalZ, ] + 1e-20) : NaNs produced

Any pointers/work around/help?

Thank you!!!

**Comment by joshua-d-campbell** [comment]
Hi @peerkarmaus,
Thanks for using our tool. I couldn't download the matrix via your Box link. I'm not sure if there is another way you can share it. 

A few quick things to check:

1) Make sure no columns are all zero. I believe that rows that are all zero should be excluded by DecontX.
2) Make sure no values are negative
3) Make sure all values are positive counts

If those things don't help, it may have to do with the cluster labels that are heuristically detected. You may want to supplying your own cluster labels using the "z" parameter.

**Comment by peerkarmaus** [comment]
Thank you for the quick reply! 

1. 
`min(colSums(mat))`
[1] 506
`min(rowSums(mat))`
[1] 3


2. 
`min(mat)`
[1] 0


3. 
`is.integer(mat)`
[1] TRUE



I provided a .zip file of the matrix in this response, so you can test it yourself.

Thank you!!!

[mat.RData.zip](https://github.com/campbio/celda/files/5064811/mat.RData.zip)

**Comment by joshua-d-campbell** [comment]
I was able to run it successfully with my version. Make sure you are using the most recent version by reinstalling from Bioconductor. You can also install from Github using devtools:

```
library(devtools)
install_github("campbio/celda")
```

Also make sure to check out the latest vignette:

https://www.bioconductor.org/packages/release/bioc/vignettes/celda/inst/doc/decontX.pdf

**Comment by peerkarmaus** [comment]
Thank you!

The github version fixed the issue.
