### ISSUE TITLE
DecontX unused argument error 

### ISSUE THREAD

**Issue by supfastjf** [campbio/celda#296]
Hello,

I ran DecontX on a raw expression matrix a couple months ago and it worked fine. I tried running the same matrix again and it is now giving me the following error: 

> Error in .local(x, ...) : 
>   unused argument (counts = c(0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
> Calls: decontX -> decontX

Here is my code: 

> library(Matrix)
> library(celda)
> 
> exprs_matrix <- readRDS("expression_matrix.rds")
> exprs_matrix_2 <- as.matrix(exprs_matrix)
> storage.mode(exprs_matrix_2) <- "integer"
> 
> exprs_decont <- decontX(counts = exprs_matrix_2, z = NULL)
> 
> saveRDS(exprs_decont, expression_matrix_decont.rds)
> 

I can share the file if necessary.

Thanks

**Comment by joshua-d-campbell** [comment]
Hi @supfastjf, 
I think in the latest version the parameter name was changed from "counts" to "x", which can either be a matrix or SingleCellExperiment object. Can you try running this:

`decontX(exprs_matrix_2)`

**Comment by supfastjf** [comment]
Whoops, you're right. It worked! Thanks!
