### ISSUE TITLE
Cluster labels and PlotDimReduce boundaries

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/celda#30]
Need to add the ability to add labels for cell clusters.

In plotDimReduceCluster, need to add ability to draw cluster labels using ggrepel. The labels should point to the centroid of each cluster.

Also, potentially interesting would be the ability to draw lines denoting the contours/boundaries around clusters.

**Comment by ykoga07** [comment]
Ability to add cluster labels implemented in #66
Still need contours
