### ISSUE TITLE
plotDimReduceCluster error

### ISSUE THREAD

**Issue by ltosti** [campbio/celda#308]
Hi there,

When I run the following

```plotDimReduceCluster(x = pc_t.sce$decontX_clusters, dim1 = umap[, 1], dim2 = umap[, 2])```

I get the following error:

```
Error in data.frame(dim1, dim2, cluster): argument "cluster" is missing, with no default
Traceback:

1. plotDimReduceCluster(x = pc_t.sce$decontX_clusters, dim1 = umap[, 
 .     1], dim2 = umap[, 2])
2. data.frame(dim1, dim2, cluster)
```

Any idea of what is causing this? If it helps, ```plotDecontXContamination(pc_t.sce)``` works without errors.

Thank you!

**Comment by joshua-d-campbell** [comment]
Hi @ltosti, I think the name of the argument is "cluster" in the case, not "x". See if this works for you:

```
plotDimReduceCluster(dim1 = umap[, 1], dim2 = umap[, 2], cluster = pc_t.sce$decontX_clusters)
```

**Comment by ltosti** [comment]
Yes, it works! Thank you for the quick reply 👍
