### ISSUE TITLE
error while using decontX on seurat data (count object) 

### ISSUE THREAD

**Issue by mbourgey** [campbio/celda#316]
Hello,

when I try to run the decontX funtion on my seurat data I raise an error:
```
> library(celda)
> te=decontX(m0.05[["RNA"]]@counts)
--------------------------------------------------
Start DecontX. Decontamination
--------------------------------------------------
Error in storage.mode(counts) <- "integer" :
  no method for coercing this S4 class to a vector
```

do you have any clue where the error comes from ?

Is it due to my environment ? or is it it an issue with decontX ?
my R version 3.6.3 
and the package have been install from BioConductor with error

Thank you

Mathieu

**Comment by Irisapo** [comment]
This is likely to be the unmatched data-type in the assay from the sce object. 
you can try to convert the matrix as basic "matrix" class. 

Can you try this before you run DecontX
```
SummarizedExperiment::assay(sce, "counts") <- as.matrix(assay(sce, "counts") )
```

**Comment by joshua-d-campbell** [comment]
Hi @mbourgey, I think if you upgrade to the newer version of decontX in R 4.0, it will fix this automatically. For the older version in R 3.6, if you are trying to use the counts from a Seurat object, you can try the following:

```
counts <- as.matrix(m0.05[["RNA"]]@counts)
storage.mode(counts) <- "integer"
result <- decontX(counts)
```

**Comment by mbourgey** [comment]
Thank you Joshua,

it have worked but not for very large counts matrix. 
I'm currently updating my R to switch to version 4 and I will try the latest version on the celda package.

I also have trouble to interpret and analyze the results of DecontX I generate with this verison as the documention and vignette does not seems to match to the older version. 

As a last question if I want to bring back the decontaminated result to Seurat what are you suggesting ?

Thank you

Mathieu

**Comment by Irisapo** [comment]
Hi @mbourgey, you can use decontaminated count matrix from DecontX to run Seurat as exactly how you used it on the original count matrix. As DecontX only removes contaminated transcripts, and doesn’t do any normalization or transformation, the decontaminated count matrix is then the cleaner version of original counts. 
In terms of code (before) using Seurat, if there is specific integer data type required by Seurat, you will need to round the decontaminated count matrix first: 

decontaminated_counts <- round(decontaminated_counts)

**Comment by mbourgey** [comment]
Thank you very much
