### ISSUE TITLE
Round or integer?

### ISSUE THREAD

**Issue by faraz89** [campbio/celda#318]
Hi,

I just wanted to clarify if we are suppose to get "integer" or "round" values when extracting decontaminated decontXcounts?

**Is it acceptable to do:**

counts <- sobject@assays@data$decontXcounts
mode(counts) <- "integer"

And then use counts for seurat downstream analysis.

**Or do we need to do:**

counts <- round(sobject@assays@data$decontXcounts)

And use the above for seurat downstream analysis.

Are they both acceptable?

Thanks,
Faraz

**Comment by joshua-d-campbell** [comment]
Hi @faraz89, each of those methods will produce integer values and thus should work. Note that you can retrieve the decontaminated counts with the command:

`decontXcounts(sobject)`

Also, if you are plugging into a down-stream tool that does not require integer counts (like Seurat), you do not **have** to round them.
