### ISSUE TITLE
Error while using 'recursiveSplitModule'

### ISSUE THREAD

**Issue by linxy29** [campbio/celda#331]
Hi,

I'm trying to run 'recursiveSplitModule' on a sce object. The data I used is 10x data. When I run 'recursiveSplitModule', I got the following error:

**Error in rowSums(counts) : 'x' must be an array of at least two dimensions**

The code I used is:

```
data_dir <- 'D:/Data/kidney/rawData/NK08/filtered_feature_bc_matrix'
sce_NK08 <- read10xCounts(data_dir)
## select features
sce_NK08 <- selectFeatures(sce_NK08)
```

Any idea how I can fix this error? Many thanks.

**Comment by zhewa** [comment]
Hi @linxy29,

Thanks for trying out our package. Can you make sure you have the latest Bioconductor release (v1.6.1) of Celda package installed by checking the following dependencies?
- Bioconductor version is 3.12. You can check this by running `BiocManager::version()` in R.
- R version >= 4.0. You can check this by running `sessionInfo()` in R.

If possible, can you provide the output of `sessionInfo()` after loading `library(celda)`? This will greatly help with debugging.

Thanks

**Comment by joshua-d-campbell** [comment]
Hi @linxy29, my guess is that the class of the matrix is still in sparse format. If you type `class(counts(sce_NK08))` you may see something like `"dgCMatrix"` from the Matrix package. If this is the case, to get it to work with the current Bioconductor version of `celda`, you can run these commands:

```
counts(sce_NK08) <- as.matrix(counts(sce_NK08))
storage.mode(counts(sce_NK08)) <- "integer"
```

Note that a recent update to the development version of celda can handle sparse and/or numeric matrices. You can install the development version with devtools:

```
install.package("devtools")
devtools::install_github("campbio/celda@devel")
```

and it should work without having to convert the matrix.

**Comment by linxy29** [comment]
Thanks, @zhewa and @joshua-d-campbell. After updating to the development version, the problem is solved.
