### ISSUE TITLE
use of decontXcounts in subseq

### ISSUE THREAD

**Issue by Sa753** [campbio/celda#344]
Dear team,

Thank you for the useful tool. May I ask if I provided a matrix of raw counts to the decontX function and I got the output as a list, what should I do next to use it in seurat object for subsequent analysis?.

For example, should I add it as an assay in seurat and use the counts to perform the clustering and differential expression?

Thanks

**Comment by joshua-d-campbell** [comment]
Hi @Sa753, thanks for your question. Yes, you can take the "decontXcounts" matrix (which is returned as an item in the list) and add it to a Seurat object like you would the original raw counts matrix. The values in the decontXcounts matrix are no longer integers and some people like to round them to make them integers again. You should also assess the levels of contamination. See this tutorial for more information on plots you can make to help with this:

https://celda.camplab.net/v1.9.2/index.html
