### ISSUE TITLE
Error in fitTrendVar(fm, fv, ...)

### ISSUE THREAD

**Issue by ayeTown** [campbio/celda#351]
I get the following error when I try to run the `decontX` function: `Error in fitTrendVar(fm, fv, ...) : need at least 4 points for non-linear curve fitting`. I have a SingleCellExperiment object with 32285 genes and 13317834 cells. So a lot of cells. The only filters I applied were to exclude cells total UMI count less than 10 and exclude genes which are not expressed at all. Should I increase the total UMI count filter for excluding cells? I don't want to decrease the number of cells drastically before running this function. What is the recommended number of cells?

**Comment by ayeTown** [comment]
I was able to fix this by loading the Matrix library.

**Comment by joshua-d-campbell** [comment]
I believe this error can be prevented by us importing the Matrix package as a dependency in the decontX functions. But we will test it.

**Comment by joshua-d-campbell** [comment]
This was fixed in version 1.11.1.
