### ISSUE TITLE
Algorithm stuck at last iteration in Estimating contamination

### ISSUE THREAD

**Issue by ayeTown** [campbio/celda#352]
My code seems to be running much faster if I subset by batch/sample. However, the code doesn't continue once the algorithm has converged. I adjusted the convergence to be 0.01. It seems to get stuck here: `Completed iteration: 15 | converge: 0.009935` What portion of the code after EM is taking so long? Also, couldn't you speed it up in the case of sample labels by parallelizing?

**Comment by joshua-d-campbell** [comment]
Hi @ayeTown, which version of celda are you using? We just recently made a fix to this last step to make it much faster which is available in versions 1.9.3 and 1.10.0. You can install the latest stable version from GitHub with devtools:

```
library(devtools)
install_github("campbio/celda")
```

I would be curious to know how many cells you have on average per sample and how long it is taking it to run. We are always looking for ways to improve speed for large datasets.

**Comment by ayeTown** [comment]
I checked the package version and it is 1.6.1, so I will try and update and get back to you. I have a total of ~13 million cells and ~32 k genes. I have cells which have at least one UMI, which is why the number is so high. However, the totals are based on six samples combined, so in the function I specify `batch` to be the sample ID. I have not filtered any of the genes. What filtering do you recommend beforehand? In terms of gene-level and cell-level filtering.
