### ISSUE TITLE
decontX output not found

### ISSUE THREAD

**Issue by hsriniva1104** [campbio/celda#360]
Hi, my code ran correctly. I am using cellranger dataset.

I can't find this
colData(pbmc4k)$decontX_contamination

my object shows
![Screen Shot 2022-02-10 at 4 18 02 PM](https://user-images.githubusercontent.com/99451777/153519307-c4430cf5-d2fe-4c97-affe-51dff1c2c2ea.png)

It also shows colData not found
Here's my sessionInfo()
![Screen Shot 2022-02-10 at 4 17 07 PM](https://user-images.githubusercontent.com/99451777/153519342-cb583b75-0ce1-4cba-93f7-e54752bed9ba.png)

I also could not find plotDecontXContamination. I only found these functions.
![Screen Shot 2022-02-10 at 4 18 59 PM](https://user-images.githubusercontent.com/99451777/153519495-71e9d5d7-41c8-4b54-8502-8a3ed84137bc.png)

How do I access my output and what am I doing wrong?
Thanks!

**Comment by joshua-d-campbell** [comment]
Hello @hsriniva1104, please update to a later version of celda (e.g. 1.10). I believe this will fix your issues as the output has been changed somewhat. The algorithm should be much faster as well.  

If the input was just a matrix (or sparse matrix), then the output will be a list with the contamination located in `obj$contamination` and the new decontaminated counts matrix in `res$decontXcounts`. If the input is an SCE object, then the output will be an SCE object. The `colData` function will only work with SCE objects to get the contamination.
