### ISSUE TITLE
decontX failure in all matrix types

### ISSUE THREAD

**Issue by CMSimpson8** [campbio/celda#369]
I've been trying to use DecontX to decontaminate my matrix and have tried setting the matrix to integer, as suggested before. It comes up with this error:

Error in if (min(x) == 0) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In log(t(eta)[globalZ, ] + 1e-20) : NaNs produced

based in this, I attempted to run it as a logical matrix, which worked on a small data set but came up with an error from
EigenMatMultInt: Warning wrong R type for mapping matrix
when input a larger data set

Isn't DecontX supposed to run on integer matrices? Can anyone help me on this issue?

I'm running a test matrix from my read count matrix, of 10 columns, but I want to run the larger data set for my analysis. Ideally I don't want to loose the expression numbers by converting it into a logical matrix.

**Comment by joshua-d-campbell** [comment]
Hi @CMSimpson8, thanks for trying out our tool! Can you first tell me the version of R and celda you are using? You can get the version of celda by typing `packageVersion("celda")`. If you are using an older version (less than 1.13.0), I would suggest updating celda. If you are installing directly from Bioconductor, then you may need to upgrade to R 4.2 to get the latest version of the package in Bioconductor 3.15. You can also install the latest version directly from GitHub using devtools:

```
library(devtools)
install_github("campbio/celda")
```

Newer versions of celda should be able to use any standard numeric matrix. The could be a full matrix (i.e. class "matrix") or a sparse matrix (i.e. "dgCMatrix" class from the Matrix package). The matrix should not contain any negative values. Could you show me the class of your matrix by typing `class(m)` where `m` is the variable containing the matrix? Lastly, could you show the first few values in the matrix by typing `m[1:10,1:10]`.

**Comment by joshua-d-campbell** [comment]
A minor typo in my previous comment, the latest version of celda on Bioconductor is 1.12.0.
