### ISSUE TITLE
Function for setting seed

### ISSUE THREAD

**Issue by joshua-d-campbell** [campbio/celda#37]
There should be a single utility function that is called to set the seed from all other functions. This function should handle the case where the seed is set to null rather than having that check in every other function that needs to set the seed

**Comment by definitelysean** [comment]
The accepted solution from [our previous Bioconductor issue](https://github.com/Bioconductor/Contributions/issues/910), as specified by @joshua-d-campbell and approved of by the reviewer:

> We are trying to figure out how to balance these opposing forces and have two potential thoughts: (1) We could allow the user to set the ‘seed’ argument to NULL and then the calls to ‘set.seed()’ will be bypassed with ‘if’ statements. This would allow an advanced user the option and flexibility to deactivate seed setting for the (likely rare) workflows that require this precise control. A user that will want to perform this level of advanced analysis will also be generally be advanced enough to understand, handle, and record ‘set.seed’ manually. (2) Another option is to use the “dqrng” package for random seed generation so we do not change R’s internal .Random.seed variable. We will document that fact that the randomization for other packages using “dqrng” may be affected.

**Comment by definitelysean** [comment]
Closed in #38
