### ISSUE TITLE
celdaGridSearch S4 object bug

### ISSUE THREAD

**Issue by Irisapo** [campbio/celda#39]
celdaGridSearch throws error 
seems that the object "mod" created before extracting 'finalLogLik is not an S4 object. Didn't dig too much into it, only to list the code and error here: 

```
a = simulateCells()     
res = celdaGridSearch(counts = a$counts, model="celda_CG", params.test = list(K=5, L= 10) )
```

Error: 
```
Error in FUN(X[[i]], ...) :     
trying to get slot "finalLogLik" from an object (class "celda_CG") that is not an S4 object
```

**Comment by zhewa** [comment]
Hi @Irisapo 

Can you provide a reproducible example of the error? I tried the following and it works fine.
```
a = simulateCells(model="celda_CG")
res = celdaGridSearch(counts = a$counts, model="celda_CG", params.test = list(K=5, L= 10) )
```
Thanks.

**Comment by Irisapo** [comment]
my bad. didn't build the package, but only loaded from the celda packge path, which caused the problem. 
once I built the package, it works just fine. 
Thanks
