### ISSUE TITLE
Installing on M1 Macbook fails

### ISSUE THREAD

**Issue by kotr98** [campbio/celda#395]
Hi,

when I try to install the package, I get the error:

1: package ‘multipanelfigure’ is not available for this version of R. It also seems that it has been removed from the CRAN repository.

I am not able to install it manually as well. Has anyone else faced this problem and how can I solve it?

Installing the package on a separate linux cluster worked for me with the same R version (R version 4.3.1 (2023-06-16)
Platform: x86_64-conda-linux-gnu (64-bit)).

my sessionInfo() is:

R version 4.3.1 (2023-06-16)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.5.2

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.11.0

locale:
[1] de_DE.UTF-8/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

time zone: Europe/Berlin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.4.5.9000 usethis_2.2.2      

loaded via a namespace (and not attached):
 [1] R6_2.5.1          fastmap_1.1.1     magrittr_2.0.3    remotes_2.4.2.1  
 [5] cachem_1.0.8      glue_1.6.2        memoise_2.0.1     lifecycle_1.0.3  
 [9] ps_1.7.5          cli_3.6.1         processx_3.8.2    sessioninfo_1.2.2
[13] callr_3.7.3       vctrs_0.6.4       pkgload_1.3.3     compiler_4.3.1   
[17] prettyunits_1.2.0 tools_4.3.1       purrr_1.0.2       pkgbuild_1.4.2   
[21] ellipsis_0.3.2    crayon_1.5.2      rlang_1.1.1       fs_1.6.3

**Comment by joshua-d-campbell** [comment]
Sorry @kotr98, this is a recent development that we are in the process of fixing. The multipanelfigure package has been removed from CRAN. You should be able to manually install the older version of the package with this command: 

```
library(devtools)
install_version("multipanelfigure", version = "2.1.2", repos = "http://cran.us.r-project.org")
```

And then hopefully install celda. We will hopefully have a hotfix out shortly that removes this dependency.

**Comment by joshua-d-campbell** [comment]
Ah okay, it looks like other dependencies were also removed from CRAN. You can manually install these as well. Can you try the following code:

```
library(devtools)
install_version("assertive.properties", version = "0.0.5", repos = "http://cran.us.r-project.org")
install_version("assertive.types", version = "0.0.3", repos = "http://cran.us.r-project.org")
install_version("multipanelfigure", version = "2.1.2", repos = "http://cran.us.r-project.org")
```

**Comment by kotr98** [comment]
Works! Thank you very much for your quick and straightforward help!

**Comment by joshua-d-campbell** [comment]
Thanks, glad it worked! I am reopening the page so others can see this. We will close it once we fixed the issue in the code.

**Comment by kotr98** [comment]
In case anyone else struggles with this in the future: it is extra hard to get it running in a conda env. In this case, it will always fail at the compilation of the RccpArmadillo package. 
To solve this, add -DHAVE_WORKING_LOG1P in your conda envs $R_HOME/etc/Makeconf at the CPPFLAGS flag. Simply export PKG_CPPFLAGS="-DHAVE_WORKING_LOG1P" does not work.
