### ISSUE TITLE
Error: package or namespace load failed for ‘celda’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):  there is no package called ‘GenomeInfoDbData’

### ISSUE THREAD

**Issue by zijunmeng** [campbio/celda#400]
Hi,

when I try to install the package by using conda, I get the error:

Error: package or namespace load failed for ‘celda’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘GenomeInfoDbData’

Actually I have downloaded the GenomeInfoDbData package using conda, I dont known how to install celda package,please help me. 

Installing the package on a separate linux cluster worked for me with the same R version (R version 4.3.1 (2023-06-16)
Platform: x86_64-conda-linux-gnu (64-bit)).

here is my conda list:

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
argcomplete               1.12.3             pyhd3eb1b0_0  
atk-1.0                   2.36.0               ha1a6a79_0  
binutils_impl_linux-64    2.38                 h2a08ee3_1  
bioconductor-basilisk     1.2.1             r40hdfd78af_0    bioconda
bioconductor-basilisk.utils 1.2.2             r40hdfd78af_0    bioconda
bioconductor-beachmat     2.6.4             r40h399db7b_1    bioconda
bioconductor-biobase      2.50.0            r40hd029910_1    bioconda
bioconductor-biocgenerics 0.36.0            r40hdfd78af_1    bioconda
bioconductor-biocneighbors 1.8.2             r40h399db7b_0    bioconda
bioconductor-biocparallel 1.24.1            r40h399db7b_0    bioconda
bioconductor-biocsingular 1.6.0             r40h399db7b_1    bioconda
bioconductor-bluster      1.0.0             r40hf484d3e_0    paul.martin-2
bioconductor-celda        1.6.1             r40h399db7b_1    bioconda
bioconductor-complexheatmap 2.6.2             r40hdfd78af_1    bioconda
bioconductor-data-packages 20230718             hdfd78af_1    bioconda
bioconductor-delayedarray 0.16.3            r40hd029910_0    bioconda
bioconductor-delayedmatrixstats 1.12.3            r40hdfd78af_0    bioconda
bioconductor-densvis      1.00.6            r40h399db7b_0    bioconda
bioconductor-edger        3.32.1            r40h399db7b_0    bioconda
bioconductor-genomeinfodb 1.26.4            r40hdfd78af_0    bioconda
bioconductor-genomeinfodbdata 1.2.4             r40hdfd78af_2    bioconda
bioconductor-genomicranges 1.42.0            r40hd029910_1    bioconda
bioconductor-hdf5array    1.18.1            r40hd029910_0    bioconda
bioconductor-iranges      2.24.1            r40hd029910_0    bioconda
bioconductor-limma        3.46.0            r40hd029910_1    bioconda
bioconductor-mast         1.16.0            r40hdfd78af_1    bioconda
bioconductor-matrixgenerics 1.2.1             r40hdfd78af_0    bioconda
bioconductor-rhdf5        2.34.0            r40h399db7b_1    bioconda
bioconductor-rhdf5filters 1.2.0             r40h399db7b_1    bioconda
bioconductor-rhdf5lib     1.12.1            r40hd029910_0    bioconda
bioconductor-s4vectors    0.28.1            r40hd029910_0    bioconda
bioconductor-scater       1.18.6            r40hdfd78af_0    bioconda
bioconductor-scran        1.18.5            r40h399db7b_0    bioconda
bioconductor-scuttle      1.0.4             r40h399db7b_0    bioconda
bioconductor-singlecellexperiment 1.12.0            r40hdfd78af_1    bioconda
bioconductor-sparsematrixstats 1.2.1             r40h399db7b_0    bioconda
bioconductor-summarizedexperiment 1.20.0            r40hdfd78af_1    bioconda
bioconductor-xvector      0.30.0            r40hd029910_1    bioconda
bioconductor-zlibbioc     1.36.0            r40hd029910_1    bioconda
boost-cpp                 1.81.0               he95ae9e_0    conda-forge
bwidget                   1.9.14               ha770c72_1    conda-forge
bzip2                     1.0.8                h7b6447c_0  
c-ares                    1.23.0               hd590300_0    conda-forge
ca-certificates           2023.11.17           hbcca054_0    conda-forge
cairo                     1.16.0               hb05425b_5  
curl                      7.86.0               h2283fc2_1    conda-forge
expat                     2.5.0                hcb278e6_1    conda-forge
fftw                      3.3.10          nompi_hc118613_108    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
gcc_impl_linux-64         12.1.0              hea43390_17    conda-forge
gdk-pixbuf                2.42.10              h5eee18b_0  
gettext                   0.21.1               h27087fc_0    conda-forge
gfortran_impl_linux-64    12.1.0              h1db8e46_17    conda-forge
ghostscript               9.18                          1    bioconda
giflib                    5.2.1                h5eee18b_3  
glib                      2.78.1               hfc55251_0    conda-forge
glib-tools                2.78.1               hfc55251_0    conda-forge
glpk                      5.0                  h445213a_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
gobject-introspection     1.72.0          py310hbb6d50b_2  
graphite2                 1.3.13            h58526e2_1001    conda-forge
graphviz                  2.50.0               h1b29801_1  
gsl                       2.7.1                h6e86dc7_1  
gtk2                      2.24.33              h73c1081_2  
gts                       0.7.6                hb67d8dd_3  
gxx_impl_linux-64         12.1.0              hea43390_17    conda-forge
harfbuzz                  5.3.0                h418a68e_0    conda-forge
icu                       70.1                 h27087fc_0    conda-forge
imagemagick               7.1.0_27        pl5321hae5efcc_0    conda-forge
importlib-metadata        4.11.3          py310h06a4308_0  
importlib_metadata        4.11.3               hd3eb1b0_0  
jbig                      2.1                  hdba287a_0  
jpeg                      9e                   h5eee18b_1  
jq                        1.5                           0    bioconda
kernel-headers_linux-64   2.6.32              he073ed8_16    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h08a2579_0    conda-forge
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      4.0.0                h27087fc_0    conda-forge
libblas                   3.9.0           20_linux64_openblas    conda-forge
libcurl                   7.86.0               h2283fc2_1    conda-forge
libdeflate                1.14                 h166bdaf_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-devel_linux-64     12.1.0              h1ec3361_17    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgd                     2.3.3                h6a678d5_3  
libgfortran-ng            13.2.0               h69a702a_3    conda-forge
libgfortran5              13.2.0               ha4646dd_3    conda-forge
libglib                   2.78.1               hebfc3b9_0    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.4                h166bdaf_0    conda-forge
liblapack                 3.9.0           20_linux64_openblas    conda-forge
libnghttp2                1.58.0               h47da74e_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.25          pthreads_h413a1c8_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
librsvg                   2.54.4               h7abd40a_0    conda-forge
libsanitizer              12.1.0              ha89aaad_17    conda-forge
libsqlite                 3.44.2               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-devel_linux-64  12.1.0              h1ec3361_17    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
libtiff                   4.4.0                h82bc61c_5    conda-forge
libtool                   2.4.6             h6a678d5_1009  
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp                   1.2.4                h11a3e52_1  
libwebp-base              1.2.4                h5eee18b_1  
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.10.3               hca2bb57_4    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
make                      4.3                  hd18ef5c_1    conda-forge
ncurses                   6.4                  h6a678d5_0  
ninja                     1.10.2               h06a4308_5  
ninja-base                1.10.2               hd09550d_5  
nspr                      4.35                 h6a678d5_0  
nss                       3.89.1               h6a678d5_0  
openjpeg                  2.4.0                h3ad879b_0  
openssl                   3.2.0                hd590300_1    conda-forge
pandoc                    2.12                 h06a4308_3  
pango                     1.50.12              h382ae3d_0    conda-forge
pcre2                     10.40                hc3806b6_0    conda-forge
perl                      5.32.1          0_h5eee18b_perl5  
pip                       23.3.1          py310h06a4308_0  
pixman                    0.42.2               h59595ed_0    conda-forge
pkg-config                0.29.2               h1bed415_8  
poppler                   22.12.0              h381b16e_0  
poppler-data              0.4.11               h06a4308_1  
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
python                    3.10.13         hd12c33a_0_cpython    conda-forge
pyyaml                    6.0.1           py310h5eee18b_0  
r-abind                   1.4_5           r40hc72bb7e_1003    conda-forge
r-askpass                 1.1               r40hcfec24a_2    conda-forge
r-assertive.base          0.0_9             r40hc72bb7e_0    conda-forge
r-assertive.files         0.0_2           r40hc72bb7e_1003    conda-forge
r-assertive.numbers       0.0_2           r40h6115d3f_1003    conda-forge
r-assertive.properties    0.0_5             r40hc72bb7e_0    conda-forge
r-assertive.types         0.0_3           r40hc72bb7e_1004    conda-forge
r-assertthat              0.2.1             r40hc72bb7e_2    conda-forge
r-backports               1.4.1             r40hcfec24a_0    conda-forge
r-base                    4.0.5                hb87df5d_8    conda-forge
r-base64enc               0.1_3           r40hcfec24a_1004    conda-forge
r-beeswarm                0.4.0             r40hcfec24a_1    conda-forge
r-bh                      1.78.0_0          r40hc72bb7e_0    conda-forge
r-bitops                  1.0_7             r40h06615bd_0    conda-forge
r-brew                    1.0_7             r40hc72bb7e_0    conda-forge
r-brio                    1.1.3             r40hcfec24a_0    conda-forge
r-bslib                   0.4.0             r40hc72bb7e_0    conda-forge
r-cachem                  1.0.6             r40hcfec24a_0    conda-forge
r-cairo                   1.6_0             r40h06615bd_0    conda-forge
r-callr                   3.7.2             r40hc72bb7e_0    conda-forge
r-catools                 1.18.2            r40h7525677_0    conda-forge
r-circlize                0.4.15            r40hc72bb7e_0    conda-forge
r-cli                     3.4.1             r40h7525677_0    conda-forge
r-clue                    0.3_60            r40hcfec24a_0    conda-forge
r-cluster                 2.1.3             r40h8da6f51_0    conda-forge
r-codetools               0.2_18            r40hc72bb7e_0    conda-forge
r-collections             0.3.5             r40hcfec24a_0    conda-forge
r-colorspace              2.0_3             r40h06615bd_0    conda-forge
r-combinat                0.0_8           r40hc72bb7e_1003    conda-forge
r-commonmark              1.8.0             r40h06615bd_0    conda-forge
r-cowplot                 1.1.1             r40hc72bb7e_0    conda-forge
r-cpp11                   0.4.2             r40hc72bb7e_0    conda-forge
r-crayon                  1.5.1             r40hc72bb7e_0    conda-forge
r-crosstalk               1.2.0             r40hc72bb7e_0    conda-forge
r-curl                    4.3.2             r40hcfec24a_0    conda-forge
r-cyclocomp               1.1.0           r40hc72bb7e_1004    conda-forge
r-data.table              1.14.2            r40hcfec24a_0    conda-forge
r-dbscan                  1.1_10            r40h03ef668_0    conda-forge
r-deldir                  1.0_6             r40h8da6f51_0    conda-forge
r-dendextend              1.16.0            r40hc72bb7e_0    conda-forge
r-desc                    1.4.2             r40hc72bb7e_0    conda-forge
r-diffobj                 0.3.5             r40hcfec24a_0    conda-forge
r-digest                  0.6.29            r40h03ef668_0    conda-forge
r-doparallel              1.0.17            r40hc72bb7e_0    conda-forge
r-dotcall64               1.0_1             r40h859d828_0    conda-forge
r-doubletfinder           2.0.3                     r40_0    paul.martin-2
r-dplyr                   1.0.10            r40h7525677_0    conda-forge
r-dqrng                   0.3.0             r40h7525677_0    conda-forge
r-ellipsis                0.3.2             r40hcfec24a_0    conda-forge
r-enrichr                 3.1               r40hc72bb7e_0    conda-forge
r-evaluate                0.16              r40hc72bb7e_0    conda-forge
r-fansi                   1.0.3             r40h06615bd_0    conda-forge
r-farver                  2.1.1             r40h7525677_0    conda-forge
r-fastmap                 1.1.0             r40h03ef668_0    conda-forge
r-fields                  14.1              r40h8da6f51_0    conda-forge
r-filelock                1.0.2           r40hcfec24a_1002    conda-forge
r-fitdistrplus            1.1_8             r40hc72bb7e_0    conda-forge
r-fnn                     1.1.3.1           r40h7525677_0    conda-forge
r-fontawesome             0.3.0             r40hc72bb7e_0    conda-forge
r-foreach                 1.5.2             r40hc72bb7e_0    conda-forge
r-formatr                 1.12              r40hc72bb7e_0    conda-forge
r-fs                      1.5.2             r40h7525677_1    conda-forge
r-futile.logger           1.4.3           r40hc72bb7e_1003    conda-forge
r-futile.options          1.0.1           r40hc72bb7e_1002    conda-forge
r-future                  1.28.0            r40hc72bb7e_0    conda-forge
r-future.apply            1.9.1             r40hc72bb7e_0    conda-forge
r-generics                0.1.3             r40hc72bb7e_0    conda-forge
r-getoptlong              1.0.5             r40hc72bb7e_0    conda-forge
r-ggbeeswarm              0.6.0           r40ha770c72_1003    conda-forge
r-ggdendro                0.1.23            r40hc72bb7e_0    conda-forge
r-ggplot2                 3.3.6             r40hc72bb7e_0    conda-forge
r-ggrastr                 1.0.1             r40hc72bb7e_0    conda-forge
r-ggrepel                 0.9.1             r40h03ef668_0    conda-forge
r-ggridges                0.5.4             r40hc72bb7e_0    conda-forge
r-globaloptions           0.1.2             r40ha770c72_0    conda-forge
r-globals                 0.16.1            r40hc72bb7e_0    conda-forge
r-glue                    1.6.2             r40h06615bd_0    conda-forge
r-goftest                 1.2_3             r40h06615bd_0    conda-forge
r-gplots                  3.1.3             r40hc72bb7e_0    conda-forge
r-gridextra               2.3             r40hc72bb7e_1003    conda-forge
r-gridgraphics            0.5_1             r40hc72bb7e_0    conda-forge
r-gtable                  0.3.1             r40hc72bb7e_0    conda-forge
r-gtools                  3.9.3             r40h06615bd_0    conda-forge
r-here                    1.0.1             r40hc72bb7e_0    conda-forge
r-hexbin                  1.28.2            r40h8da6f51_0    conda-forge
r-highr                   0.9               r40hc72bb7e_0    conda-forge
r-hms                     1.1.2             r40hc72bb7e_0    conda-forge
r-htmltools               0.5.3             r40h7525677_0    conda-forge
r-htmlwidgets             1.5.4             r40hc72bb7e_0    conda-forge
r-httpuv                  1.6.6             r40h7525677_0    conda-forge
r-httr                    1.4.4             r40hc72bb7e_0    conda-forge
r-ica                     1.0_3             r40hc72bb7e_0    conda-forge
r-igraph                  1.3.4             r40hb34fc8a_0    conda-forge
r-irlba                   2.3.5             r40h5f7b363_0    conda-forge
r-isoband                 0.2.5             r40h03ef668_0    conda-forge
r-iterators               1.0.14            r40hc72bb7e_0    conda-forge
r-jquerylib               0.1.4             r40hc72bb7e_0    conda-forge
r-jsonlite                1.8.0             r40h06615bd_0    conda-forge
r-kernsmooth              2.23_20           r40h742201e_0    conda-forge
r-knitr                   1.40              r40hc72bb7e_0    conda-forge
r-labeling                0.4.2             r40hc72bb7e_1    conda-forge
r-lambda.r                1.2.4             r40hc72bb7e_1    conda-forge
r-languageserver          0.3.13            r40h06615bd_0    conda-forge
r-later                   1.2.0             r40h03ef668_0    conda-forge
r-lattice                 0.20_45           r40hcfec24a_0    conda-forge
r-lazyeval                0.2.2             r40hcfec24a_2    conda-forge
r-leiden                  0.4.3             r40hc72bb7e_0    conda-forge
r-lifecycle               1.0.2             r40hc72bb7e_0    conda-forge
r-lintr                   3.0.1             r40hc72bb7e_0    conda-forge
r-listenv                 0.8.0             r40hc72bb7e_1    conda-forge
r-lmtest                  0.9_40            r40h8da6f51_0    conda-forge
r-locfit                  1.5_9.4           r40hcfec24a_1    conda-forge
r-lsei                    1.3_0             r40hc3ea6d6_1    conda-forge
r-magick                  2.7.3             r40h03ef668_0    conda-forge
r-magrittr                2.0.3             r40h06615bd_0    conda-forge
r-maps                    3.4.0             r40hcfec24a_0    conda-forge
r-mass                    7.3_58.1          r40h06615bd_0    conda-forge
r-matrix                  1.4_1             r40h0154571_0    conda-forge
r-matrixstats             0.62.0            r40h06615bd_0    conda-forge
r-mcmcprecision           0.4.0             r40h306847c_2    conda-forge
r-memoise                 2.0.1             r40hc72bb7e_0    conda-forge
r-mgcv                    1.8_40            r40h0154571_0    conda-forge
r-mime                    0.12              r40hcfec24a_0    conda-forge
r-miniui                  0.1.1.1         r40hc72bb7e_1002    conda-forge
r-multipanelfigure        2.1.2             r40hc72bb7e_1    conda-forge
r-munsell                 0.5.0           r40hc72bb7e_1004    conda-forge
r-nlme                    3.1_159           r40h8da6f51_0    conda-forge
r-npsurv                  0.5_0             r40hc72bb7e_0    conda-forge
r-openssl                 2.0.3             r40h1f3e0c5_0    conda-forge
r-parallelly              1.32.1            r40hc72bb7e_0    conda-forge
r-patchwork               1.1.2             r40hc72bb7e_0    conda-forge
r-pbapply                 1.5_0             r40hc72bb7e_0    conda-forge
r-pheatmap                1.0.12            r40hc72bb7e_2    conda-forge
r-pillar                  1.8.1             r40hc72bb7e_0    conda-forge
r-pkgbuild                1.3.1             r40hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r40hc72bb7e_1    conda-forge
r-pkgload                 1.3.0             r40hc72bb7e_0    conda-forge
r-plotly                  4.10.0            r40hc72bb7e_0    conda-forge
r-plyr                    1.8.7             r40h7525677_0    conda-forge
r-png                     0.1_7           r40hcfec24a_1004    conda-forge
r-polyclip                1.10_0            r40h7525677_2    conda-forge
r-praise                  1.0.0           r40hc72bb7e_1005    conda-forge
r-prettyunits             1.1.1             r40hc72bb7e_1    conda-forge
r-proc                    1.18.0            r40h03ef668_0    conda-forge
r-processx                3.7.0             r40h06615bd_0    conda-forge
r-progress                1.2.2             r40hc72bb7e_2    conda-forge
r-progressr               0.11.0            r40hc72bb7e_0    conda-forge
r-promises                1.2.0.1           r40h03ef668_0    conda-forge
r-ps                      1.7.1             r40h06615bd_0    conda-forge
r-purrr                   0.3.4             r40hcfec24a_1    conda-forge
r-r.cache                 0.16.0            r40hc72bb7e_0    conda-forge
r-r.methodss3             1.8.2             r40hc72bb7e_0    conda-forge
r-r.oo                    1.25.0            r40hc72bb7e_0    conda-forge
r-r.utils                 2.12.0            r40hc72bb7e_0    conda-forge
r-r6                      2.5.1             r40hc72bb7e_0    conda-forge
r-ragg                    1.2.2             r40hc1f6985_0    conda-forge
r-rann                    2.6.1             r40h7525677_2    conda-forge
r-rappdirs                0.3.3             r40hcfec24a_0    conda-forge
r-rcolorbrewer            1.1_3             r40h785f33e_0    conda-forge
r-rcpp                    1.0.9             r40h7525677_1    conda-forge
r-rcppannoy               0.0.19            r40h7525677_0    conda-forge
r-rcpparmadillo           0.11.2.3.1        r40h9f5de39_0    conda-forge
r-rcppeigen               0.3.3.9.2         r40h43535f1_0    conda-forge
r-rcpphnsw                0.4.1             r40h7525677_0    conda-forge
r-rcppparallel            5.1.5             r40h7525677_0    conda-forge
r-rcppprogress            0.4.2             r40hc72bb7e_1    conda-forge
r-rcpptoml                0.1.7             r40h03ef668_1    conda-forge
r-rcurl                   1.98_1.8          r40h06615bd_0    conda-forge
r-rematch2                2.1.2             r40hc72bb7e_1    conda-forge
r-remotes                 2.4.2             r40hc72bb7e_0    conda-forge
r-repr                    1.1.4             r40h785f33e_0    conda-forge
r-reshape2                1.4.4             r40h03ef668_1    conda-forge
r-reticulate              1.30              r40ha503ecb_1    conda-forge
r-rex                     1.2.1             r40hc72bb7e_0    conda-forge
r-rjson                   0.2.21            r40h7525677_1    conda-forge
r-rlang                   1.0.6             r40h7525677_0    conda-forge
r-rmarkdown               2.16              r40hc72bb7e_0    conda-forge
r-rocr                    1.0_11            r40hc72bb7e_1    conda-forge
r-roxygen2                7.2.1             r40h7525677_0    conda-forge
r-rpart                   4.1.16            r40hcfec24a_0    conda-forge
r-rprojroot               2.0.3             r40hc72bb7e_0    conda-forge
r-rspectra                0.16_1            r40h9f5de39_0    conda-forge
r-rstudioapi              0.14              r40hc72bb7e_0    conda-forge
r-rsvd                    1.0.5             r40hc72bb7e_0    conda-forge
r-rtsne                   0.16              r40h37cf8d7_0    conda-forge
r-sass                    0.4.2             r40h7525677_0    conda-forge
r-scales                  1.2.1             r40hc72bb7e_0    conda-forge
r-scattermore             0.8               r40h06615bd_0    conda-forge
r-sctransform             0.3.2             r40h29659fb_0    paul.martin-2
r-seurat                  4.0.0             r40h29659fb_0    paul.martin-2
r-seuratobject            4.0.0             r40h29659fb_0    paul.martin-2
r-shape                   1.4.6             r40ha770c72_0    conda-forge
r-shiny                   1.7.2             r40h785f33e_0    conda-forge
r-sitmo                   2.0.2             r40h7525677_0    conda-forge
r-snow                    0.4_4             r40hc72bb7e_0    conda-forge
r-sourcetools             0.1.7           r40h03ef668_1002    conda-forge
r-sp                      1.5_0             r40h06615bd_0    conda-forge
r-spam                    2.9_1             r40hb361e29_0    conda-forge
r-spatstat                1.64_1            r40h0357c0b_0    conda-forge
r-spatstat.core           2.4_4             r40h7525677_0    conda-forge
r-spatstat.data           2.2_0             r40hc72bb7e_0    conda-forge
r-spatstat.geom           2.4_0             r40h06615bd_0    conda-forge
r-spatstat.linnet         2.3_2             r40hcfec24a_0    conda-forge
r-spatstat.random         2.2_0             r40h7525677_0    conda-forge
r-spatstat.sparse         2.1_1             r40h06615bd_0    conda-forge
r-spatstat.utils          2.3_1             r40h06615bd_0    conda-forge
r-statmod                 1.4.37            r40hc3ea6d6_0    conda-forge
r-stringdist              0.9.8             r40hcfec24a_1    conda-forge
r-stringi                 1.7.8             r40h30a9eb7_0    conda-forge
r-stringr                 1.4.1             r40hc72bb7e_0    conda-forge
r-styler                  1.7.0             r40hc72bb7e_0    conda-forge
r-survival                3.4_0             r40h06615bd_0    conda-forge
r-sys                     3.4               r40hcfec24a_0    conda-forge
r-systemfonts             1.0.4             r40hef9c87a_0    conda-forge
r-tensor                  1.5             r40hc72bb7e_1003    conda-forge
r-testthat                3.1.4             r40h7525677_0    conda-forge
r-textshaping             0.3.6             r40h9354b80_2    conda-forge
r-tibble                  3.1.8             r40h06615bd_0    conda-forge
r-tidyr                   1.2.1             r40h7525677_0    conda-forge
r-tidyselect              1.1.2             r40hc72bb7e_0    conda-forge
r-tinytex                 0.42              r40hc72bb7e_0    conda-forge
r-utf8                    1.2.2             r40hcfec24a_0    conda-forge
r-uwot                    0.1.14            r40h7525677_0    conda-forge
r-vctrs                   0.4.1             r40h7525677_0    conda-forge
r-vipor                   0.4.5           r40hc72bb7e_1003    conda-forge
r-viridis                 0.6.2             r40hc72bb7e_0    conda-forge
r-viridislite             0.4.1             r40hc72bb7e_0    conda-forge
r-waldo                   0.4.0             r40hc72bb7e_0    conda-forge
r-withr                   2.5.0             r40hc72bb7e_0    conda-forge
r-writexls                6.4.0             r40hc72bb7e_0    conda-forge
r-xfun                    0.33              r40h7525677_0    conda-forge
r-xml2                    1.3.3             r40h7525677_1    conda-forge
r-xmlparsedata            1.0.5             r40hc72bb7e_0    conda-forge
r-xtable                  1.8_4             r40hc72bb7e_3    conda-forge
r-yaml                    2.3.5             r40h06615bd_0    conda-forge
r-zoo                     1.8_11            r40h06615bd_0    conda-forge
readline                  8.2                  h5eee18b_0  
sed                       4.8                  he412f7d_0    conda-forge
setuptools                68.0.0          py310h06a4308_0  
sqlite                    3.41.2               h5eee18b_0  
sysroot_linux-64          2.12                he073ed8_16    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tktable                   2.10                 h0c5db8f_5    conda-forge
toml                      0.10.2             pyhd3eb1b0_0  
tzdata                    2023c                h04d1e81_0  
wheel                     0.41.2          py310h06a4308_0  
xmltodict                 0.13.0          py310h06a4308_0  
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.7                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.4.2                h5eee18b_0  
yaml                      0.2.5                h7b6447c_0  
yq                        2.12.0             pyhd3eb1b0_0  
zipp                      3.11.0          py310h06a4308_0  
zlib                      1.2.13               hd590300_5    conda-forge
zstd                      1.5.5                hfc55251_0    conda-forge

**Comment by joshua-d-campbell** [comment]
Hi @zijunmeng, thanks for using our tool. It looks like this is a broader issue with Bioconda and the GenomeInfoDbData package. For now, you can try earlier versions. I was able to get this to work: 

```
conda create --name celda python=3.8
conda activate celda

conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda config --set channel_priority strict

conda install bioconductor-celda=1.14.0
```
